Feature/inoue
c-app-dev-waseda-group-f/waseda-c-application-development-2020-spring-group-work pull request #33
Opened 2020-07-18 07:30 UTC by tomoino

READMEにタスク開始から完了までの流れを詳細に書きました。

2020-07-18 08:12 UTC, yangminshun requested changes
> 基本的に下記の作業の流れが考えられます。

の部分と重なると思うので、元の部分を削除しませんか？

---

和欧混在の場合、半角スペースを入れたほうがきれいのではと思いますが、
個人的な好みなので、嫌だったら気にしないで。。

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1.  GitHubのissuesからタスク一覧を確認します。
```suggestion
1.  GitHub の Issues からタスク一覧を確認します。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1. できそうなタスクをクリックしてissueのページに移動します。内容を確認したら、Assignees
```suggestion
1. できそうなタスクをクリックして Issue のページに移動します。内容を確認したら、Assignees
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1. 自分のPCで作業をしていきます。(画像はコマンドラインを使う場合)
```suggestion
1. 自分の PC で作業をしていきます。（画像はコマンドラインを使う場合）
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +    1. masterブランチにいることを確認します。
```suggestion
    1. master ブランチにいることを確認します。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +    1. git pullしてmasterを最新のものに更新します。
```suggestion
    1. `git pull` して master ブランチを最新のものに更新します。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +    1. 自分の担当するissueに合わせてブランチを切ります。
```suggestion
    1. 自分の担当する issue に合わせてブランチを切ります。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +    1. 問題なく動くことを確認したら、git add(変更したファイルの登録)、git commit(変更内容にコメントを付ける、#issue番号を書くのを忘れずに)します。
```suggestion
    1. 問題なく動くことを確認したら、`git add`（変更したファイルの登録）、`git commit`（変更内容にコメントを付ける、#issue 番号を書くのを忘れずに）します。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +    1. git push(GitHubへのファイルのアップロード)をします。
```suggestion
    1. `git push`（GitHub へのファイルのアップロード）をします。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1. GitHubでPull Request（＝他の人への確認依頼）を送ります。Pull requestsタブからCompare & pull requestを選択します。
```suggestion
1. GitHub で Pull Request（＝他の人への確認依頼）を送ります。Pull requests タブから Compare & pull request を選択します。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1. 右上のReviewersから確認してもらいたい人を選択して、Create pull request。
```suggestion
1. 右上の Reviewers から確認してもらいたい人を選択して、Create pull request。
```

2020-07-18 08:12 UTC, yangminshun commented on README.md
> +1. 確認してもらってOKが出ると、Squash and mergeが押せるようになるのでこれを押してmerge(masterブランチに自分の作業を反映すること)して作業完了です。
```suggestion
1. 確認してもらって OK が出ると、Squash and merge が押せるようになるのでこれを押して merge（master ブランチに自分の作業を反映すること）して作業完了です。
```

2020-07-19 08:18 UTC, tomoino commented
ご指摘いただきありがとうございます。指摘箇所修正してみました。いかがでしょう？

2020-07-19 08:44 UTC, yangminshun approved these changes
感謝します！

2020-07-19 09:04 UTC, merged