[update]main: collided with enemies
c-app-dev-waseda-group-f/waseda-c-application-development-2020-spring-group-work pull request #41
Opened 2020-07-21 01:51 UTC by tomoino

敵との衝突判定を追加。いったん、衝突後printfしてexitする処理を実装。
Game Overの文字を表示するなどの処理にするのが良いかと思われますが、実装がすぐにできるものでもなかったのとissue分けた方が良いかもと思ったのでそこまでは実装していないです。

2020-07-21 02:04 UTC, yangminshun requested changes
検証で

> ｜壁｜自｜
> ーーーーー
> ｜敵｜　｜

から、自機を下へ一方向移動する

![image](https://user-images.githubusercontent.com/33303880/88004426-f7dd2700-cb41-11ea-9877-4985f180411b.png)

> ｜壁｜　｜
> ーーーーー
> ｜敵｜自｜

と、結果衝突と判定されました。

これは期待される動きでしょうか？

2020-07-21 02:04 UTC, yangminshun commented on main.c
> +
ここのスペースは何のためですか？

2020-07-21 02:04 UTC, yangminshun commented on main.c
> +
ここのスペースは何のためですか？

2020-07-21 02:04 UTC, yangminshun commented on main.c
> -
ここのスペースの削除は何のためですか？

2020-07-21 02:04 UTC, yangminshun commented on main.c
> +            printf("GAME OVER");
ここに関しては、これは正しいと思います。

そもそも衝突以降どうなるかに関してはどうでもいい（この issue と関係ない）と思います。

2020-07-21 02:04 UTC, abest2016 commented on main.c
> +        if (sqrt(pow(player.coordinate.x - enemyList.enemies[i].coordinate.x, 2) + pow(player.coordinate.y - enemyList.enemies[i].coordinate.y, 2)) < gameBoard.lengthOfBlock) {
```suggestion
        if (sqrt(pow(player.coordinate.x - enemyList.enemies[i].coordinate.x, 2) + pow(player.coordinate.y - enemyList.enemies[i].coordinate.y, 2)) < 1) {
```

2020-07-22 07:35 UTC, tomoino commented
ご指摘のあった個所を修正しました。
衝突判定の感度が高すぎたので少し緩めました。

2020-07-23 06:44 UTC, yangminshun submitted a review, later dismissed

2020-07-24 07:26 UTC, tomoino commented
conflictを解消しました。お手数ですが再度確認をお願いします。

2020-07-24 07:29 UTC, yangminshun approved these changes

2020-07-24 07:30 UTC, merged