時間計測の基盤整備
c-app-dev-waseda-group-f/waseda-c-application-development-2020-spring-group-work pull request #47
Opened 2020-07-24 06:21 UTC by abest2016

2020-07-24 06:52 UTC, abest2016 commented
時間制限を設定した上で、残り時間を 0 秒まで表示する。

2020-07-25 05:36 UTC, tomoino requested changes
下記のようなエラーが出てコンパイルできません。

`
main.c: In function ‘finishGameIfTimeLimitAchieved’:
main.c:87:9: warning: implicit declaration of function ‘_difftime64’; did you mean ‘difftime’? [-Wimplicit-function-declaration]
     if (_difftime64(clock(), startTime) / 1000 > timeLimit) {
         ^~~~~~~~~~~
         difftime
/tmp/ccKpOGcT.o: In function `finishGameIfTimeLimitAchieved':
main.c:(.text+0x41e): undefined reference to `_difftime64'
/tmp/ccKpOGcT.o: In function `timerFunc':
main.c:(.text+0x588): undefined reference to `_difftime64'
collect2: error: ld returned 1 exit status
`

_difftime64の引数は__time64_t型ですので、difftimeを使うのが良いかと思います。
また、その場合でもclock()が返すのはclock_t型なので一緒に使えるかはよくわからないです。
time_tで統一する場合は、time関数を使う方法があるようです。
参考：http://www9.plala.or.jp/sgwr-t/lib/difftime.html

2020-07-25 06:12 UTC, abest2016 commented
`difftime` に直しました。

`clock()` の部分に関しては、ミリ秒を表現したくて使ったのですが、私の方に特に問題ないのです。

2020-07-25 07:06 UTC, tomoino reviewed
コンパイルできるのは確認しましたが、Time Leftが0sのままになっています。
そちらではどうでしょう？

2020-07-25 07:42 UTC, abest2016 commented
わざとそうしました。

カウントダウンという意味で、マイナス秒になっても意味がないと思います。

2020-07-25 11:17 UTC, tomoino approved these changes
お疲れ様です。
カウントダウンではなく経過時間を表示するのはOKだと思います。
値が増えることなく0sのままだったのが気になっていました。
仕様でそうしているようでしたらMergeしていただいて結構です。

2020-07-25 11:22 UTC, merged